### ISSUE TITLE
ImportError : DLL load failed

### ISSUE THREAD

**Issue by liggest** [mrkn/numpy.rb#6]
It seems I could not import numpy into Ruby by using `require 'numpy'`

- OS: Windows 10
- Ruby version: ruby 2.6.6p146 [x64-mingw32]
- PyCall version: 1.4.1
- Python version: Python 3.7.2 [MSC v.1915 64 bit (AMD64)] :: Anaconda custom (64-bit) on win32
- Numpy version: 1.16.4

`import numpy as np` in Python and `math = PyCall.import_module("math")` in Ruby work fine.

The error logs are like:
```
PyCall::PyError: <class 'ImportError'>: DLL load failed: The specified module could not be found.
  File "D:\Python\Anaconda\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import _distributor_init
  File "D:\Python\Anaconda\lib\site-packages\numpy\_distributor_init.py", line 34, in <module>
    from . import _mklinit

from X:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/pycall-1.4.1/lib/pycall.rb:74:in `import_module'
Caused by LoadError: cannot load such file -- numpy
from X:/Ruby/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```

**Comment by liggest** [comment]
I recently found it to be solved by updating both Numpy and PyCall
